title: "SOFTBRIDGE"
description: "Software Development Services"
keywords: "IT solutions, software development, Mobile App Development, Active Directory, ADFS, .NET applications, system integration, Microsoft Exchange"
author:
  name: "SOFTBRIDGE"
  email: "info@softbridge.com.my"
baseurl: ""
url: "http://www.softbridge.com.my"
theme: minima
plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "assets/images/"
    values:
      sitemap: false



